# Generated by Django 5.1.7 on 2025-05-06 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('transcription', 'Medical Transcription'), ('clinical_notes', 'Clinical Notes Generation'), ('form_automation', 'Form Automation'), ('other', 'Other')], default='other', max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('configuration_data', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('transcription', 'Transcription'), ('clinical_notes', 'Clinical Notes'), ('form_fill', 'Form Auto-fill'), ('other', 'Other')], default='other', max_length=50)),
                ('input_data_reference', models.CharField(blank=True, max_length=255)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('result_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failure', 'Failure')], default='success', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.aimodelconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
