# Generated by Django 5.1.6 on 2025-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_clinicalnote_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('transcription', 'Transcription'), ('summarization', 'Summarization'), ('clinical_note', 'Clinical Note Generation'), ('speech_to_text', 'Speech to Text'), ('form_filling', 'Form Auto-Filling'), ('qa', 'Question Answering')], max_length=50)),
                ('api_endpoint', models.URLField()),
                ('configuration_data', models.TextField(blank=True, default='{}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'verbose_name_plural': 'AI Model Configurations',
                'ordering': ['name'],
            },
        ),
    ]
