# Generated by Django 5.1.7 on 2025-05-21 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_aimodelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_data', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_in_person', models.BooleanField(default=True)),
                ('appt_virtual', models.BooleanField(default=True)),
                ('appt_emergency', models.BooleanField(default=False)),
                ('appt_duration_standard', models.IntegerField(default=30)),
                ('appt_duration_extended', models.IntegerField(default=60)),
                ('appt_lead_time', models.IntegerField(default=24)),
                ('appt_future_limit', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='provider.provider')),
            ],
        ),
    ]
