# Generated by Django 5.1.7 on 2025-05-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_appointment_options_appointment_status_and_more'),
        ('provider', '0002_provider_clinicalnote_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='provider.provider'),
        ),
    ]
