# Generated by Django 5.1.6 on 2025-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_prescription_options_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
