# Generated by Django 5.1.6 on 2025-05-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_appointment_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dose',
            new_name='dosage',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='name',
            new_name='medication_name',
        ),
    ]
