# Generated by Django 5.1.6 on 2025-05-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_dose_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
