# Generated by Django 5.1.6 on 2025-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_prescription_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
