# Generated by Django 5.1.7 on 2025-05-22 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_prescription_expires'),
        ('provider', '0004_providerschedule_providersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'time'], name='common_appo_patient_560f61_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'time'], name='common_appo_doctor__f5af4e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'time'], name='common_appo_status_b0db49_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'status', 'created_at'], name='common_mess_recipie_15c18d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='common_mess_sender__eba9af_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['subject'], name='common_mess_subject_19ad85_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='common_pres_patient_7b0301_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'created_at'], name='common_pres_doctor__0ec4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medication_name'], name='common_pres_medicat_f9987c_idx'),
        ),
    ]
