# Generated by Django 5.1.7 on 2025-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ohip_number', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('medication_name', models.CharField(max_length=200)),
                ('current_dosage', models.CharField(max_length=100)),
                ('medication_duration', models.CharField(max_length=100)),
                ('last_refill_date', models.DateField()),
                ('preferred_pharmacy', models.CharField(max_length=200)),
                ('new_medical_conditions', models.TextField(blank=True)),
                ('new_medications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('information_consent', models.BooleanField()),
                ('pharmacy_consent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
