# Generated by Django 5.1.6 on 2025-05-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_update_patient_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='ohip_number',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='information_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='last_refill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='pharmacy_consent',
            field=models.BooleanField(default=False),
        ),
    ]
