# Generated by Django 5.1.7 on 2025-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_name', '0003_appointment_message_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='patientregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
