# Generated by Django 5.1.7 on 2025-04-05 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_name', '0004_alter_appointment_options_alter_blogpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('transcription', 'Medical Transcription'), ('clinical_notes', 'Clinical Notes Generation'), ('form_automation', 'Form Automation'), ('other', 'Other')], default='other', max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('configuration_data', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('transcription', 'Transcription'), ('clinical_notes', 'Clinical Notes'), ('form_fill', 'Form Auto-fill'), ('other', 'Other')], default='other', max_length=50)),
                ('input_data_reference', models.CharField(blank=True, max_length=255)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('result_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failure', 'Failure')], default='success', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme_name.aimodelconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('lab_req', 'Lab Requisition'), ('sick_note', 'Sick Note'), ('referral', 'Referral Letter'), ('insurance', 'Insurance Form'), ('prescription', 'Prescription Form'), ('other', 'Other')], default='other', max_length=50)),
                ('template_content', models.TextField()),
                ('requires_patient_data', models.BooleanField(default=True)),
                ('requires_provider_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_data', models.TextField()),
                ('rendered_content', models.TextField(blank=True)),
                ('pdf_storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_name.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_recording_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('transcription_text', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='theme_name.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_generated_text', models.TextField(blank=True)),
                ('provider_edited_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'AI Generated'), ('reviewed', 'Provider Reviewed'), ('finalized', 'Finalized')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='theme_name.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_notes', to=settings.AUTH_USER_MODEL)),
                ('transcription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme_name.recordingsession')),
            ],
        ),
    ]
