# Generated by Django 5.1.7 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_name', '0005_aimodelconfig_aiusagelog_documenttemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user_type', models.CharField(choices=[('provider', 'Healthcare Provider'), ('patient', 'Patient'), ('admin', 'Healthcare Administrator'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (9am-12pm)'), ('afternoon', 'Afternoon (1pm-5pm)'), ('evening', 'Evening (5pm-7pm)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recordingsession',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='template',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generateddocument',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PrescriptionRequest',
        ),
        migrations.DeleteModel(
            name='AIModelConfig',
        ),
        migrations.DeleteModel(
            name='AIUsageLog',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ClinicalNote',
        ),
        migrations.DeleteModel(
            name='RecordingSession',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
