# Generated by Django 5.1.7 on 2025-05-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_clinicalnote_provider_and_more'),
        ('theme_name', '0006_demorequest_remove_aiusagelog_model_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientregistration',
            options={},
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='ehr_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='erpnext_id',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='ohip_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='pharmacy_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='virtual_care_consent',
            field=models.BooleanField(default=False),
        ),
    ]
